server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/identity_service
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  #    password: 123456789
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "aa0eefb42c914aa7afc7dc6bf7d5915c8f5f84dcfb50f315678cd4f9a02e5e3a"
  valid-duration: 15 # in milliseconds
  refreshable-duration: 120 # in milliseconds
